version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    image: backend-api
    ports:
      - 4000:4000
    volumes:
      - /my-app/node_modules
      - ./backend:/my-app
    # env_file: .env
    networks:
      - backend
      - frontend
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    image: frontend-client
    ports:
      - 3000:3000
    volumes:
      - /my-app/node_modules
      - ./frontend:/my-app
    networks:
      - frontend
networks:
  backend:
  frontend:
